CREATE TABLE IF NOT EXISTS restaurants (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    restaurant_name TEXT NOT NULL,
    street TEXT NOT NULL,
    telephone TEXT NOT NULL,
    hrs TEXT NOT NULL,
);

CREATE TABLE IF NOT EXISTS beers (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    beer_name TEXT NOT NULL,
    brewery TEXT NOT NULL,
    style TEXT NOT NULL,
    abv TEXT NOT NULL,
    country TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS taps (
    restaurant INTEGER REFERENCES restaurants(id) NOT NULL,
    beer INTEGER REFERENCES beers(id) NOT NULL,
    CONSTRAINT id PRIMARY KEY (restaurant_id, beer_id)
);